routes/web.php
<?php

use Faker\Factory as Faker;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('out');
Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::resource('product', 'ProductController');
    Route::resource('user', 'UserController');
    Route::get('invoice', 'InvoiceController@index')->name('invoice.index');
    Route::get('invoice/{invoice}', 'InvoiceController@show')->name('invoice.show');
});

resources/views/layouts/partials/footer.blade.php
<footer class="page-footer">
    <div class="pd-t-4 pd-b-0 pd-x-20">
       <div class="tx-10 tx-uppercase">
          <p class="pd-y-10 mb-0">Copyright&copy; 2019 | All rights reserved. | Created By <a href="http://themeforest.net/user/colorlibcode" target="_blank">ColorlibCode</a></p>
       </div>
    </div>
 </footer>

resources/views/layouts/partials/header.blade.php
<div class="page-header">
    <div class="search-form">
       <form action="#" method="GET">
          <div class="input-group">
             <input class="form-control search-input" name="search" placeholder="Type something..." type="text"/>
             <span class="input-group-btn">
             <span id="close-search"><i class="ion-ios-close-empty"></i></span>
             </span>
          </div>
       </form>
    </div>
    <!--================================-->
    <!-- Page Header  Start -->
    <!--================================-->
    <nav class="navbar navbar-expand-lg">
       <ul class="list-inline list-unstyled mg-r-20">
          <!-- Mobile Toggle and Logo -->
          <li class="list-inline-item align-text-top"><a class="hidden-md hidden-lg" href="#" id="sidebar-toggle-button"><i class="ion-navicon tx-20"></i></a></li>
          <!-- PC Toggle and Logo -->
          <li class="list-inline-item align-text-top"><a class="hidden-xs hidden-sm" href="#" id="collapsed-sidebar-toggle-button"><i class="ion-navicon tx-20"></i></a></li>
       </ul>
       <!--================================-->
       <!-- Mega Menu Start -->
       <!--================================-->
       <div class="collapse navbar-collapse">
          <ul class="navbar-nav mr-auto">
          </ul>
       </div>
       <!--/ Mega Menu End-->
       <!--/ Brand and Logo End -->
       <!--================================-->
       <!-- Header Right Start -->
       <!--================================-->
       <div class="header-right pull-right">
          <ul class="list-inline justify-content-end">

             <!--/ Messages Dropdown End -->
             <!--================================-->
             <!-- Profile Dropdown Start -->
             <!--================================-->
             <li class="list-inline-item dropdown">
             <a  href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="select-profile">Hi, {{ Auth::user()->name }} !</span><img src="https://via.placeholder.com/100x100" class="img-fluid wd-35 ht-35 rounded-circle" alt=""></a>
                <div class="dropdown-menu dropdown-menu-right dropdown-profile shadow-2">
                   <div class="user-profile-area">
                      <div class="user-profile-heading">
                         <div class="profile-thumbnail">
                            <img src="https://via.placeholder.com/100x100" class="img-fluid wd-35 ht-35 rounded-circle" alt="">
                         </div>
                         <div class="profile-text">
                            <h6>{{ Auth::user()->name }}</h6>
                            <span>{{ Auth::user()->email }}</span>
                         </div>
                      </div>
                      <a href="{{ route('out') }}" class="dropdown-item"><i class="icon-power" aria-hidden="true"></i> Sign-out</a>
                   </div>
                </div>
             </li>
             <!-- Profile Dropdown End -->
             <!--================================-->
          </ul>
       </div>
       <!--/ Header Right End -->
    </nav>
 </div>

resources/views/layouts/partials/sidebar.blade.php
<div class="page-sidebar">
    <div class="logo">
       <a class="logo-img" href="index.html">
       <img class="desktop-logo" src="{{ asset('light/assets/images/logo.png') }}" alt="">
       <img class="small-logo" src="{{ asset('light/assets/images/small-logo.png') }}" alt="">
       </a>
       <i class="ion-ios-close-empty" id="sidebar-toggle-button-close"></i>
    </div>
    <!--================================-->
    <!-- Sidebar Menu Start -->
    <!--================================-->
    <div class="page-sidebar-inner">
       <div class="page-sidebar-menu">
          <ul class="accordion-menu">
             <li class="{{ (request()->is('dashboard')) ? 'active' : '' }}">
                <a href="{{ route('dashboard.index') }}"><i data-feather="dashboard"></i>
                <span>Dashboard</span></a>
             </li>
             <li class="{{ (request()->is('product*')) ? 'active' : '' }}">
                <a href="{{ route('product.index') }}"><i data-feather="box"></i>
                <span>Product</span></a>
             </li>
             <li class="{{ request()->is('user*') ? 'active' : '' }}">
                <a href="{{ route('user.index') }}"><i data-feather="users"></i>
                <span>User</span></a>
             </li>
             <li class="{{ request()->is('invoice*') ? 'active' : '' }}">
                <a href="{{ route('invoice.index') }}"><i data-feather="users"></i>
                <span>Invoice</span></a>
             </li>
          </ul>
       </div>
    </div>
    <!--/ Sidebar Menu End -->
    <!--================================-->
    <!-- Sidebar Footer Start -->
    <!--================================-->
    <div class="sidebar-footer">
       <a class="pull-left" href="page-profile.html" data-toggle="tooltip" data-placement="top" data-original-title="Profile">
       <i data-feather="user" class="ht-15"></i></a>
       <a class="pull-left " href="mailbox.html" data-toggle="tooltip" data-placement="top" data-original-title="Mailbox">
       <i data-feather="mail" class="ht-15"></i></a>
       <a class="pull-left" href="page-unlock.html" data-toggle="tooltip" data-placement="top" data-original-title="Lockscreen">
       <i data-feather="lock" class="ht-15"></i></a>
       <a class="pull-left" href="page-singin.html" data-toggle="tooltip" data-placement="top" data-original-title="Sing Out">
       <i data-feather="log-out" class="ht-15"></i></a>
    </div>
    <!--/ Sidebar Footer End -->
 </div>