routes/web.php
<?php

use Faker\Factory as Faker;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('out');
Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::resource('product', 'ProductController');
    Route::resource('user', 'UserController');
    Route::get('invoice', 'InvoiceController@index')->name('invoice.index');
    Route::get('invoice/{invoice}', 'InvoiceController@show')->name('invoice.show');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::paginate(10);
        return view('page.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('page.product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = new product;
        $product->name = $request->name;
        $product->base_cost = $request->base_cost;
        $product->price = $request->price;
        $product->save();

        return redirect()->route('product.index')->with('alert-success', 'Berhasil menambah product');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('page.product.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $product->name = $request->name;
        $product->base_cost = $request->base_cost;
        $product->price = $request->price;
        $product->save();

        return redirect()->route('product.index')->with('alert-success', 'Berhasil mengubah data product');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();

        return redirect()->route('product.index')->with('alert-success', 'Berhasil mnghapus data product');
    }
}

resources/views/page/product/create.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-12 col-lg-12">
    <div class="card pd-20 wd-80p m-auto">
        <div class="card-header">
            <h4 class="card-header-title">
             Add Product
          </h4>
        </div>
        <div class="card-body pd-0">
            <form action="{{ route('product.store') }}" method="post">
            @csrf
            <div class="form-layout form-layout-5">
                <div class="row mg-t-20">
                    <label class="col-sm-4 form-control-label"><span class="tx-danger">*</span> Product Name:</label>
                    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                        <input type="text" class="form-control" placeholder="Enter Product Name" name="name" required>
                    </div>
                </div>
                <div class="row mg-t-20">
                    <label class="col-sm-4 form-control-label"><span class="tx-danger">*</span> Base Cost:</label>
                    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                        <input type="text" class="form-control" placeholder="Enter Base Cost" name="base_cost" required>
                    </div>
                </div>
                <div class="row mg-t-20">
                    <label class="col-sm-4 form-control-label"><span class="tx-danger">*</span> Price:</label>
                    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                        <input type="text" class="form-control" placeholder="Enter Price" name="price" required>
                    </div>
                </div>
                <div class="row mg-t-30">
                    <div class="col-sm-8 mg-l-auto">
                        <div class="form-layout-footer">
                            <button type="submit" class="btn btn-custom-primary">Create</button>
                            <a href="{{ route('product.index') }}" class="btn btn-secondary">Cancel</a>
                        </div>
                        <!-- form-layout-footer -->
                    </div>
                    <!-- col-8 -->
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/page/product/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-12 col-lg-12">
    <div class="card pd-20 wd-80p m-auto">
        <div class="card-header">
            <h4 class="card-header-title">
             Edit Product
          </h4>
        </div>
        <div class="card-body pd-0">
            <form action="{{ route('product.update', $product) }}" method="post">
                @csrf
                @method('PATCH')
                <div class="form-layout form-layout-5">
                    <div class="row mg-t-20">
                        <label class="col-sm-4 form-control-label"><span class="tx-danger">*</span> Product Name:</label>
                        <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                            <input type="text" class="form-control" placeholder="Enter Product Name" value="{{ $product->name }}" name="name" required>
                        </div>
                    </div>
                    <div class="row mg-t-20">
                        <label class="col-sm-4 form-control-label"><span class="tx-danger">*</span> Base Cost:</label>
                        <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                            <input type="text" class="form-control" placeholder="Enter Base Cost" value="{{ $product->base_cost }}" name="base_cost" required>
                        </div>
                    </div>
                    <div class="row mg-t-20">
                        <label class="col-sm-4 form-control-label"><span class="tx-danger">*</span> Price:</label>
                        <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                            <input type="text" class="form-control" placeholder="Enter Price" value="{{ $product->price }}" name="price" required>
                        </div>
                    </div>
                    <div class="row mg-t-30">
                        <div class="col-sm-8 mg-l-auto">
                            <div class="form-layout-footer">
                                <button type="submit" class="btn btn-custom-primary">Save</button>
                                <a href="{{ route('product.index') }}" class="btn btn-secondary">Cancel</a>
                            </div>
                            <!-- form-layout-footer -->
                        </div>
                        <!-- col-8 -->
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/page/product/index.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-12 col-lg-12">
    <div class="card pd-20 wd-80p m-auto">
       <div class="card-header">
          <h4 class="card-header-title">
             Product
          </h4>
          <div class="float-right">
            <a href="{{ route('product.create') }}" class="btn btn-sm btn-success">Add</a>
          </div>
       </div>
       <div class="card-body pd-0 collapse show" id="collapse2">
          <table class="table table-striped">
             <thead>
                <tr>
                   <th>No</th>
                   <th>Product Name</th>
                   <th>Base Cost</th>
                   <th>Price</th>
                   <th>#</th>
                </tr>
             </thead>
             <tbody>
                @forelse ($products as $product)
                    <tr>
                        <td>{{ (($products->currentPage()-1) * $products->perPage()) + $loop->iteration }}</td>
                        <td>{{ $product->name }}</td>
                        <td>{{ $product->base_cost }}</td>
                        <td>{{ $product->price }}</td>
                        <td>
                            <a href="{{ route('product.edit', $product->id) }}">
                                <button class="btn btn-sm btn-warning">Edit</button>
                            </a>
                            <button id="delete" data-title="{{$product->name}}" href="{{ route('product.destroy', $product) }}" class="btn btn-sm btn-danger">Delete</button>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5" align="center">Product Not Found</td>
                    </tr>
                @endforelse
             </tbody>
          </table>
          {{ $products->links() }}
       </div>
    </div>
 </div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')
<script type="text/javascript">
$('button#delete').on('click', function(){
    var href = $(this).attr('href');
    var title = $(this).data('title');
    swal({
      title: "Anda yakin akan menghapus product bernama "+ title +" ?",
      text: "Setelah dihapus data tidak dapat dikembalikan !",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        $('#deleteForm').attr('action', href);
        $('#deleteForm').submit();
      }
    });
});
</script>
@endsection